### ISSUE TITLE
implement camera buttons in website

### ISSUE THREAD

**Issue by meganrm** [allen-cell-animated/simularium-website#139]
## Use Case

Allow users to switch between pan and rotate, and use key board keys to control the camera in addition to the buttons. 
## Solution

- camera buttons are on bottom right of viewer panel oriented vertically
- text is only in tooltips, not next to camera buttons
- mockup can be found here https://zpl.io/V0oLjdE
- hotkeys (moved from viewer ticket since it's better to implement these in website)
- (SHIFT/CMD modifier keys are already implemented)

**tooltips:

- rotate: "Rotate mode (SHIFT or CMD)"
- pan: "Pan mode (SHIFT or CMD)"
- zoom in: "Zoom in (↑)"
- zoom out: "Zoom out (↓)"
- reset: "Reset camera (R)"
- the first time a user toggles focus without an agent selected, warn them "Select a target agent to focus the camera."
- the rotate/pan and focus buttons' color state updates to match the current state, even if it is toggled or overridden with a key

## Alternatives

I think it would be nice to have hotkeys for the rotate and pan modes, I'll implement this as is, but here is my alternative proposal ( I know we are going to want to user test, so this is just for the future if the current system seems confusing): 

- rotate: "Rotate camera (Shift & click or R)" 
- pan: "Pan camera (Shift & click or P)"
- zoom in: "Zoom in (↑)"
- zoom out: "Zoom out (↓)"
- reset: "Reset camera(H)" (since we're going to use the home icon for this instead of the arrows)

**Comment by meganrm** [comment]
One other issue I thought of while implementing.... I think the tooltips should have lowercase letters. I think it would be reasonable for someone to try hitting "shift + r" for example to reset the camera. Right now, that will change the camera mode, but not reset the view at all. We could talk about whether that should instead reset the camera. IE the rule is you hit "shit+hotkey" ignore shift and do the hotkey action.

**Comment by blairlyons** [comment]
> @blairlyons: One other issue I thought of while implementing.... I think the tooltips should have lowercase letters. As is, I think it would be reasonable for someone to try hitting "shift + r" for example to reset the camera. Right now, that will change the camera mode, but not reset the view at all. We could talk about whether that should instead reset the camera. IE the rule is you hit "shit+hotkey" ignore shift and do the hotkey action.

I was using uppercase because it's for keys, they have the uppercase letter printed on them. I think that's usually what I've seen? If I saw "R" I'd only press R. But maybe a thing for user testing?

**Comment by blairlyons** [comment]
Takeaways from dev meeting this morning:

1. make rotate/pan tooltips conditional on state of toggle group.
If rotate is enabled, tooltips are:
- rotate: "Rotate"
- pan: "Pan (hold SHIFT)"
If pan is enabled:
- rotate: "Rotate (hold SHIFT)"
- pan: "Pan"
2. change reset tooltip to "Home view (H)" and use H as hotkey
3. don't add focus notification about selection for now
