### ISSUE TITLE
Add generate URL option to Load model menu

### ISSUE THREAD

**Issue by blairlyons** [allen-cell-animated/simularium-website#144]
## Use Case
When a user is creating URLs to share trajectories stored at public links, it would be nice if they could input the links in a text field instead of editing the URL itself, having to know the trajURL param name etc.

## Acceptance Criteria
Users can use options in the UI to input a public URL and have the viewer load data from that URL.

## Details
Add a menu item to the load model menu, "From a URL" which opens a text dialog to input a public link. I think we should also clarify what the other options in this menu are doing by changing them to "From your device" and "From examples". So the menu would be:

Load model >
- From examples
    - [examples submenu]
- From a URL
    - [URL dialog]
- From your device
    - [file dialog]

URL dialog:
Provide the URL to your public Simularium file: 
[text input field] ["Load" button]
(We currently support public Dropbox, Google Drive, and Amazon S3 links. [Learn more[link to quick start page about link generation]])

when user presses submit button, go to the URL [https://simularium.allencell.org/viewer?trajURL=[user-provided URL]] to load the user's trajectory in the viewer.

inspiration for this comes from http://3dviewer.net/index.htm

**Comment by blairlyons** [comment]
Lisa's future design for the menu is here: https://app.zeplin.io/project/5ceee2a189a82e03ffe7f8a3/screen/5f757c2453ff7537aa245a3e

It's not much different than the current one, just adds a thumbnail of the model. I think this future design needs more UX work, for example should the thumbnail be off to the side like this or next to the model title? should there be cards instead of a list of model titles? Is there other info we want to display beyond title and thumbnail? 

I think we should go ahead and add the "from a URL" option in the meantime, we could wait to change the names of the other menu items, but I think changing them would clarify the difference between the options.

**Comment by meganrm** [comment]
> Lisa's future design for the menu is here: https://app.zeplin.io/project/5ceee2a189a82e03ffe7f8a3/screen/5f757c2453ff7537aa245a3e
> 
> It's not much different than the current one, just adds a thumbnail of the model. I think this future design needs more UX work, for example should the thumbnail be off to the side like this or next to the model title? should there be cards instead of a list of model titles? Is there other info we want to display beyond title and thumbnail?
> 
> I think we should go ahead and add the "from a URL" option in the meantime, we could wait to change the names of the other menu items, but I think changing them would clarify the difference between the options.

There was another design that was a dialog box instead of a popup, but it's not there anymore @thao-do may have access to it.
