### ISSUE TITLE
Sphere agents from previous timesteps don't clear

### ISSUE THREAD

**Issue by blairlyons** [allen-cell-animated/simularium-website#148]
## Description

Performance is slow with large sphere trajectories, and for some examples, previous agents stop clearing partway through playback when frame rate is very slow. This happens on staging and prod sites, but not with current viewer example run locally.

## Expected Behavior

The smooth playback from the current viewer example should also be on staging if the staging viewer has been updated.

## Reproduction

1. Download https://aics-agentviz-data.s3.us-east-2.amazonaws.com/trajectory/springsalad_condensate_formation_Below_Ksp.simularium
2. Go to https://staging.simularium.allencell.org/viewer (or prod) and drag and drop file
3. Press play, once the playback gets about halfway done, agents from previous frames don't clear.
4. Clone current https://github.com/allen-cell-animated/simularium-viewer and run the example with `npm start`, navigate to http://localhost:8080/public/
5. Drag and drop the same file
6. Press play, playback is fast and all previous agents are cleared through the whole trajectory

**Comment by schoinh** [comment]
Oof, sorry, I got that wrong, just checked again and mesh instancing is not on staging yet! When [this PR](https://github.com/allen-cell-animated/simularium-website/pull/140) by @meganrm is approved and merged then staging will be updated with viewer v2.9.4 containing mesh intancing.

**Comment by schoinh** [comment]
No longer an issue after the above PR was merged, closing
