### ISSUE TITLE
Drag-and-drop upload shows incorrect agents when loaded after a networked model

### ISSUE THREAD

**Issue by schoinh** [allen-cell-animated/simularium-website#160]
## Description

Sometimes, when a trajectory is loaded via drag and drop after loading a networked trajectory, incorrect agents are displayed, like this:

![image](https://user-images.githubusercontent.com/12690133/124038124-7fb7ec00-d9b5-11eb-8b37-329f92584035.png)

The above is when the actin model is drag-and-dropped after loading endocytosis from the server (see repro steps below). The correct actin agents (shown in below screenshot) did flash into the viewer for a split second before the above incorrect agents above appeared and stayed, so I think there might be some unwanted requests being made during the file switch. Maybe related to @toloudis 's thought in this comment: https://github.com/allen-cell-animated/simularium-viewer/pull/128#pullrequestreview-692987415

Also lots of console errors like this:

![image](https://user-images.githubusercontent.com/12690133/124038699-69f6f680-d9b6-11eb-88e0-3c1dda5e2d95.png)

## Expected Behavior

I was expecting to see this for actin.
![image](https://user-images.githubusercontent.com/12690133/124038252-afff8a80-d9b5-11eb-92be-79d50576c6b2.png)

## Reproduction

1. Download this file https://www.dropbox.com/s/ipqad4n8c3bny75/actin.h5.simularium?dl=0
2. Go to staging
3. Load endocytosis from landing card or dropdown
4. Skip to a time like 5s by clicking on the slider
5. Drag-and-drop load the actin file downloaded from Dropbox
6. Instead of the actin model, the endocytosis model is shown in the viewer canvas, but it's all yellow, and the time is at 0.2 ns instead of the beginning time of 0 ns, and there are a lot of errors about `getColorIndexForTypeId` in the console. (See attached screenshot)
7. But if at this point you click the Play button, the actin model comes into view and starts playing from the beginning like nothing went wrong! 

## Environment

This bug is NOT reproducible in the viewer testbed alone.

**Comment by blairlyons** [comment]
might be related to data still arriving after new trajectory is loaded

**Comment by schoinh** [comment]
I just followed my repro steps and couldn't reproduce the bug. Closing! :)
