### ISSUE TITLE
Reorganize redux state

### ISSUE THREAD

**Issue by schoinh** [allen-cell-animated/simularium-website#166]
## Use Case

For a Simularium developer, it would be nice to have redux state that is organized in a way that makes sense.

## Solution

Reorganize state to (per @meganrm):

1. simFileMetaData/modelMetaData or something
would hold all the data that comes from the back end when you select a model
2. status
would hold stuff like isBuffering, isPlaying, viewerStatus
3. selection
the same as it is, just move "draggedOverViewer" to status
4. simularium
right now would just have the controller, but in the future might have all the available trajectories

Also create a base state to revert to for all the state resetting tasks, like this https://medium.com/@justintulk/best-practices-for-resetting-an-es6-react-components-state-81c0c86df98d

See discussion: https://github.com/allen-cell-animated/simularium-website/pull/88#discussion_r541460619

**Comment by schoinh** [comment]
Current state branches (`initialState`):
```javascript
metadata:
    firstFrameTime: 0,
    lastFrameTime: 0,
    timeStep: 0,
    timeUnits: null,
    agentIds: [],
    agentUiNames: [],
    plotData: [],
    simulariumFile: {
        name: "",
        data: null,
        lastModified: null,
    },
    simulariumController: null,
    viewerStatus: VIEWER_EMPTY,
    viewerError: null,

selection:
    time: 0,
    numberPanelsCollapsed: 0,
    visibleAgentKeys: {},
    highlightedAgentKeys: {},
    draggedOverViewer: false,
    agentColors: {},
    isBuffering: false,
    isPlaying: false,
```

Proposed state branches:
```javascript
metadata:   
// trajectory data received from backend
    firstFrameTime: 0,
    lastFrameTime: 0,
    timeStep: 0,
    timeUnits: null,
    agentIds: [],
    agentUiNames: [],
    plotData: [],
    simulariumFile: {
        name: "",
        data: null,
        lastModified: null,
    },

selection:    
// selections by user
    time: 0,
    numberPanelsCollapsed: 0,
    visibleAgentKeys: {},
    highlightedAgentKeys: {},
    agentColors: {},

status: // or app?
// app status
    viewerStatus: VIEWER_EMPTY,
    viewerError: null,
    draggedOverViewer: false,
    isBuffering: false,
    isPlaying: false,

simularium:
    simulariumController: null,
```

**Comment by toloudis** [comment]
Would it make sense to just stash the whole TrajectoryFileInfo as read-only state?

**Comment by meganrm** [comment]
I think it would be good to look at the current logics and make sure they sort into this organization still too.

**Comment by schoinh** [comment]
I thought about this again and wanted to check that we really want to do this.
```
viewerStatus -> status,
viewerError -> error,
draggedOverViewer -> draggedOver,
```
Is there any reason we would want to keep these as they are? Especially `viewerStatus` and `viewerError` -- the words `status` and `error` are really broad terms and I was wondering if we would ever want to keep track of a non-viewer status or error. For example in [state/viewer/types.ts](https://github.com/allen-cell-animated/simularium-website/blob/main/src/state/viewer/types.ts#L43) there are `ViewerError` and `FrontEndError` already. 

I don't have a problem making the above changes if we're sure it would be better to do so but since this was kind of a quick spontaneous addition at the meeting I wanted to double check!
