### ISSUE TITLE
Post example models for SpringSaLaD and MEDYAN

### ISSUE THREAD

**Issue by blairlyons** [allen-cell-animated/simularium-website#174]
## Use Case

It would be nice for the posted examples to include models from SpringSaLaD, MEDYAN, and Vivarium, while still keeping the "Load your own data" card near the top of the page.

## Solution

Add cards for the new models and routing for their links to the website. Data for the models is highlighted on this sheet https://docs.google.com/spreadsheets/d/1QmcCY6qu6oRQH-qzj_TMjz0CHeHMa32evP09KTBsV0w/edit?usp=sharing and thumbnails are in drive folder https://drive.google.com/drive/folders/1o_MTacfBgRCvRdq1NuAXE2OuRqEXdB82?usp=sharing

Adding these models will push the "Load your own data" card far down the page. It could be ordered so that it's always the third card to prevent that.

**Comment by schoinh** [comment]
Will add Vivarium later when backend bug is fixed.
