### ISSUE TITLE
Uninstall unused dependencies

### ISSUE THREAD

**Issue by schoinh** [allen-cell-animated/simularium-website#211]
## What needs to happen?
Find unused npm dependencies and uninstall them (remove from package.json)

## Why should we do this?
There are some dependencies that we forgot to uninstall as we deleted unused code over time. We should remove them to remove bulk and reduce confusion.

## When does this need to get done?
Not urgent but shouldn't be a big effort

**Comment by toloudis** [comment]
Are there tools that can identify unused package.json dependencies?

**Comment by schoinh** [comment]
Yeah, I ran this tool called depcheck and got this but I think I'll need to go through and human-check these too. Pretty sure some of these are used.

```
Unused dependencies
* @aics/simularium-observables-manager
* @types/victory
* momentjs
* rc-motion
* react-player-controls
* url-loader
* victory
Unused devDependencies
* @babel/cli
* @types/enzyme
* @types/jest
* @types/jsdom
* babel-loader
* css-loader
* enzyme
* eslint-plugin-react-hooks
* file-loader
* husky
* identity-obj-proxy
* jsdom
* jsdom-global
* less
* less-loader
* lint-staged
* postcss-loader
* prettier
* ts-node
* webpack-cli
Missing dependencies
* moment: ./src/components/ViewerTitle/index.tsx
```

**Comment by toloudis** [comment]
might try this one too: https://www.npmjs.com/package/npm-check

**Comment by schoinh** [comment]
Ok, I tried both. Just for future reference, neither are perfect but depcheck worked much better. npm-check listed way more deps under "unused" that were actually used (like lodash!)
