### ISSUE TITLE
Update publication for SpringSaLaD models

### ISSUE THREAD

**Issue by blairlyons** [allen-cell-animated/simularium-website#213]
## Use Case
The publication accompanying the SpringSaLaD example models was just published, and it would be nice to link to the final publication rather than the preprint and to redirect the preview link (which was published by the journal) to the final URLs for the models. 

## Acceptance Criteria
Users can follow link to final publication from the landing page cards for the SpringSaLaD models, and follow the preview links and be redirected to the final links.

## Details
Final publication is "The solubility product extends the buffering concept to heterotypic biomolecular condensates. eLife (2021)" and the link is https://elifesciences.org/articles/67176. This is also updated and highlighted on the spreadsheet https://docs.google.com/spreadsheets/d/1QmcCY6qu6oRQH-qzj_TMjz0CHeHMa32evP09KTBsV0w/edit#gid=0

Redirects:
- https://simularium.allencell.org/viewer?trajUrl=https://aics-agentviz-data.s3.us-east-2.amazonaws.com/trajectory/springsalad_condensate_formation_Below_Ksp.simularium to https://simularium.allencell.org/viewer?trajFileName=springsalad_condensate_formation_Below_Ksp.simularium
- https://simularium.allencell.org/viewer?trajUrl=https://aics-agentviz-data.s3.us-east-2.amazonaws.com/trajectory/springsalad_condensate_formation_At_Ksp.simularium to https://simularium.allencell.org/viewer?trajFileName=springsalad_condensate_formation_At_Ksp.simularium
- https://simularium.allencell.org/viewer?trajUrl=https://aics-agentviz-data.s3.us-east-2.amazonaws.com/trajectory/springsalad_condensate_formation_Above_Ksp.simularium to https://simularium.allencell.org/viewer?trajFileName=springsalad_condensate_formation_Above_Ksp.simularium

**Comment by schoinh** [comment]
Should I make that redirect a global thing, not just for these 3 trajectories? What I mean is if someone tries to load a trajectory from our S3 bucket with trajUrl but we have it available to stream via trajFileName, we should redirect to the streaming option instead?

**Comment by blairlyons** [comment]
No, just for these three specific trajectories. I didn't realize they had to give the final URLs to the publisher last week, so they gave them the preview URLs. We'd like people to be sent to the streaming option when they follow these links from eLife. But in general, users should still be able to name files they want to share the same thing as the streaming data, and generate links that go to those files.
