### ISSUE TITLE
Update link sharing instructions to add GDrive

### ISSUE THREAD

**Issue by blairlyons** [allen-cell-animated/simularium-website#214]
## Use Case
When a user checks the link sharing instructions on the tutorial page, it would be nice to if they saw "Google Drive" on the list of supported cloud providers since we now support Drive links.

## Acceptance Criteria
A user can see "Google Drive" on the list of supported cloud providers on the tutorial page.

## Details
In the "Share a link to your data" section of the tutorial (i.e. https://simularium.allencell.org/tutorial), change "currently Dropbox or Amazon S3" to "currently Dropbox, Google Drive, or Amazon S3"

**Comment by schoinh** [comment]
Will also change wording in error message so it suggests using Google Drive in addition to Dropbox and S3
