### ISSUE TITLE
Acknowledgements on landing page

### ISSUE THREAD

**Issue by blairlyons** [allen-cell-animated/simularium-website#239]
## Use Case
It would be nice if the acknowledgements for the Simularium project were posted on the website.

## Acceptance Criteria
There is a section at the bottom of the landing page listing the current acknowledgements, which pulls that information from ACKNOWLEDGEMENTS.md.

## Details
Blair will update ACKNOWLEDGEMENTS.md shortly.

In the absence of UX guidance, since we want to do this soon, I'd say add another section at the end of the landing page with the gray background (like in the "Connect with us" section), title can be "Acknowledgements" and subtitle "We'd like to thank the following people for their contributions to Simularium"

**Comment by blairlyons** [comment]
just opened a PR to update ACKNOWLEDGEMENTS.md #240

**Comment by schoinh** [comment]
Regarding the acceptance criteria: I'm not sure there is a good way to pull text directly from a markdown file into a React component or into HTML. If we want to be able to update one document and have it be auto-reflected in the landing page, I think JSON would be better? @meganrm any advice?

**Comment by schoinh** [comment]
Looks like there are some npm libraries I can use for this, I'll pick one or two and try it out

**Comment by meganrm** [comment]
yeah, i only have experience pulling in markdown data via a CMS, but should be not that much different than fetching any data file.
