### ISSUE TITLE
Load version 3 trajectoryInfo

### ISSUE THREAD

**Issue by blairlyons** [allen-cell-animated/simularium-website#246]
## Use Case
It would be nice if files with trajectoryInfo version=3 loaded in the viewer.

## Acceptance Criteria
Files with trajectoryInfo version=3 can load.

## Details
This is urgent because the released version of simulariumIO already produces version 3

**Comment by schoinh** [comment]
> I've updated the viewer version. Do we have some v3 files that we can now test? Or have the examples in the bucket been updated? It would just be good to test the new viewer version with files other than the ones I made myself.

Yes! https://allencellscience.slack.com/archives/CMQFRJPPF/p1632336364050600
