### ISSUE TITLE
The "couldn't load model panel" message flashes while loading a trajectory file

### ISSUE THREAD

**Issue by meganrm** [allen-cell-animated/simularium-website#266]
## Description

When dragging and dropping a file, the model panel briefly flashes the "couldn't load" error message before showing checkboxes 

## Expected Behavior

It should either be in a loading state or a loaded state. 

## Reproduction

Drag and drop a simularium file. 

## Environment

_Any additional information about your environment. E.g. OS version, python version, browser etc._

**Comment by schoinh** [comment]
I believe this is fixed
