### ISSUE TITLE
Sometimes agent types in left panel don't load

### ISSUE THREAD

**Issue by blairlyons** [allen-cell-animated/simularium-website#274]
## Description
Agent types don't load in left panel after first load of a trajURL page followed by drag and drop.

## Expected Behavior
Agent types should always load in the left panel.

## Reproduction
1. Go to a trajURL link, e.g. https://staging.simularium.allencell.org/viewer?trajUrl=https://aics-simularium-data.s3.us-east-2.amazonaws.com/trajectory/example_md.simularium 
2. Make sure your cache was clear (i.e. force reload page), this only happens on the first load
3. Drag and drop https://aics-simularium-data.s3.us-east-2.amazonaws.com/trajectory/json_v3/actin012_3_obj-local-url_arp2-green_arp3-pink_actin-purple.simularium
4. The left panel goes back to it's empty state 
![Screen Shot 2021-11-01 at 2 33 47 PM](https://user-images.githubusercontent.com/12102071/139746646-672dd6e9-4729-4da2-abb9-7a03ac347847.png)

## Environment
Staging

**Comment by schoinh** [comment]
Oh no! I'll look into this

**Comment by schoinh** [comment]
I can also repro this when I simply launch Simularium then drag-and-drop the above file

**Comment by meganrm** [comment]
I can't reproduce it at all. I have tried clearing my cache

**Comment by schoinh** [comment]
@meganrm I can only reproduce it on staging and prod but not dev. So strange. 

Also I'm wondering if it could be related to #266
